### ISSUE TITLE
[Blocked by main site prod] Link updates & checks, Countly review, etc.

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#69] opened 2021-07-26 22:14 UTC
- [x] Switch env var to reference the main prod site instead of main staging site
- [x] Test for broken links between sites 
- [x] Change our readme to include links to main service - pr open #103 
- [x] Confirm Countly is successfully pulling in production data from both sites
- [x] If repo switch public, reconfigure repo perms to remove any unnecessary access

**Comment by terichadbourne** [comment] 2021-07-28 15:33
I'm going to tackle the env variable now to make links work and leave the rest of this checklist here.

**Comment by terichadbourne** [comment] 2021-07-28 16:45
@jessicaschilling or @zebateira Would one of you have time to explore the remaining items here? I'm honestly not sure what the last one meant to say since there's a grammar bug. 

We are already in a public repo, and if we're removing any access from ourselves we'd do it after launch I'd think.

**Comment by jessicaschilling** [comment] 2021-07-28 16:56
@terichadbourne That last item made sense in the original checklist but not excerpted in this one: was just to make sure that we didn't have any perms granted to people simply because it was a private repo and we needed to give someone one-off visibility. TLDR: it's fine.

**Comment by jessicaschilling** [comment] 2021-07-28 16:58
NOTE: this is blocked until ...
- the Account/Profile switch gets implemented on the main site
- Countly gets set up on main site per https://github.com/web3-storage/docs/issues/83

**Comment by jessicaschilling** [comment] 2021-07-29 14:39
Currently checking all links in the docs site to make sure they work as intended.

**Comment by jessicaschilling** [comment] 2021-07-29 15:06
Merging some minor link fixes in https://github.com/web3-storage/docs/pull/114 will close this issue.

**Closed** 2021-07-29 16:20 UTC
Labels: P0, status/blocked
