### ISSUE TITLE
TBC: Set up Google Search Console for both sites 

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#91] opened 2021-07-27 15:52 UTC
Do we need to add this to Google Search Console? (check with Andy?) 

Asking JV if he's kicked this off in https://protocollabs.slack.com/archives/C02750576C8/p1627401050376900

**Comment by jessicaschilling** [comment] 2021-07-27 16:13
Per @jnthnvctr, opened an IT request for @andrewschwab for this.

**Comment by jessicaschilling** [comment] 2021-07-28 17:40
Confirmed added as a domain property in Search Console:
![image](https://user-images.githubusercontent.com/1507828/127370412-aac36895-10d6-45ec-99e6-f1c43661cd31.png)
This should cover both the main and docs sites, since subdomains are included, but it'll be a few days before crawler data starts coming in. Closing this issue.

**Closed by jessicaschilling** 2021-07-28 17:40 UTC
Labels: P2
